"use client";

import { useRouter } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: [
      {
        subtitle: "Agreement",
        text: "By accessing or using Outfevibe (outfevibe.com), you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our platform. We reserve the right to update these terms at any time, with notice provided via email or a prominent notice on the platform.",
      },
    ],
  },
  {
    title: "2. Description of Service",
    content: [
      {
        subtitle: "What Outfevibe provides",
        text: "Outfevibe is an AI-powered personal styling platform that provides outfit recommendations based on body type, skin tone, style preferences, occasion, and budget. Our services include a style persona quiz, AI outfit suggestions, a trending outfits feed, and affiliate shopping links to Indian platforms.",
      },
      {
        subtitle: "Service availability",
        text: "We strive to maintain 99% uptime but do not guarantee uninterrupted availability. We may occasionally take the platform offline for maintenance, updates, or improvements. We are not liable for any losses resulting from service downtime.",
      },
    ],
  },
  {
    title: "3. User Accounts",
    content: [
      {
        subtitle: "Account creation",
        text: "To access certain features, you must create an account using a valid email address or Google account. You must verify your email before accessing the platform. You are responsible for maintaining the confidentiality of your login credentials.",
      },
      {
        subtitle: "Account responsibility",
        text: "You are solely responsible for all activity that occurs under your account. If you suspect unauthorized access, contact us immediately at outfevibe@gmail.com. We reserve the right to suspend or terminate accounts that violate these terms.",
      },
      {
        subtitle: "One account per user",
        text: "Each person may only maintain one Outfevibe account. Creating multiple accounts to circumvent restrictions or abuse our services is prohibited.",
      },
    ],
  },
  {
    title: "4. Acceptable Use",
    content: [
      {
        subtitle: "You agree NOT to",
        text: "Use the platform for any unlawful purpose; attempt to gain unauthorized access to our systems; scrape, crawl, or extract data from the platform without permission; upload harmful, offensive, or inappropriate content; impersonate another person or entity; use automated tools or bots to interact with the platform; attempt to reverse-engineer our AI models or algorithms.",
      },
      {
        subtitle: "Content you upload",
        text: "By uploading photos or any content to Outfevibe, you confirm that you have the right to share that content and that it does not violate any third-party rights. You grant Outfevibe a limited, non-exclusive license to process your content solely for the purpose of delivering our services.",
      },
    ],
  },
  {
    title: "5. AI-Generated Recommendations",
    content: [
      {
        subtitle: "Nature of recommendations",
        text: "Outfevibe's outfit recommendations are generated by AI and are provided for informational and styling purposes only. We do not guarantee that recommendations will suit your personal taste, fit perfectly, or be available for purchase at the time of viewing.",
      },
      {
        subtitle: "No warranty on AI output",
        text: "AI-generated styling advice is not a substitute for professional fashion consultation. Results may vary based on the quality of photos uploaded, accuracy of information provided, and individual body type variations.",
      },
    ],
  },
  {
    title: "6. Affiliate Links & Purchases",
    content: [
      {
        subtitle: "Third-party platforms",
        text: "Outfevibe links to third-party e-commerce platforms including Meesho, Myntra, Ajio, Flipkart, and Amazon India. All purchases are made directly through these platforms. Outfevibe is not a party to any transaction between you and these platforms.",
      },
      {
        subtitle: "Affiliate commission",
        text: "We may earn an affiliate commission when you make a purchase through our links. This does not affect the price you pay. We are not responsible for product quality, delivery, returns, or disputes — these are governed by the respective platform's terms.",
      },
      {
        subtitle: "Price and availability",
        text: "Product prices and availability shown on Outfevibe may not always reflect real-time information. Always verify pricing and availability on the linked platform before purchasing.",
      },
    ],
  },
  {
    title: "7. Intellectual Property",
    content: [
      {
        subtitle: "Outfevibe's content",
        text: "All content on Outfevibe — including the logo, design, AI models, quiz framework, style personas, and written content — is the intellectual property of Outfevibe and is protected by applicable copyright and trademark laws.",
      },
      {
        subtitle: "Restricted use",
        text: "You may not copy, reproduce, distribute, or create derivative works from our content without explicit written permission. Personal, non-commercial use of our recommendations is permitted.",
      },
    ],
  },
  {
    title: "8. Limitation of Liability",
    content: [
      {
        subtitle: "No liability for indirect damages",
        text: "To the maximum extent permitted by law, Outfevibe shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform, including but not limited to: dissatisfaction with outfit recommendations, purchases made through affiliate links, or service interruptions.",
      },
      {
        subtitle: "Maximum liability",
        text: "Our total liability to you for any claim arising from these terms or your use of the platform shall not exceed the amount you have paid to Outfevibe in the 12 months preceding the claim (which for our currently free service is zero).",
      },
    ],
  },
  {
    title: "9. Termination",
    content: [
      {
        subtitle: "Your right to terminate",
        text: "You may delete your account and stop using Outfevibe at any time by contacting us at outfevibe@gmail.com or through your profile settings.",
      },
      {
        subtitle: "Our right to terminate",
        text: "We reserve the right to suspend or permanently terminate your account if you violate these Terms of Service, engage in fraudulent activity, or abuse our platform or other users. We will provide notice where reasonably possible.",
      },
    ],
  },
  {
    title: "10. Governing Law",
    content: [
      {
        subtitle: "Jurisdiction",
        text: "These Terms of Service are governed by the laws of India. Any disputes arising from these terms or your use of Outfevibe shall be subject to the exclusive jurisdiction of the courts of India.",
      },
    ],
  },
  {
    title: "11. Contact",
    content: [
      {
        subtitle: "Reach us",
        text: "For any questions, concerns, or legal notices regarding these Terms of Service, please contact us at outfevibe@gmail.com. We aim to respond to all inquiries within 48 hours.",
      },
    ],
  },
];

export default function TermsOfServicePage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-black text-white">

      {/* NAV */}
      <header className="sticky top-0 z-50 backdrop-blur-xl border-b border-neutral-800/40 bg-black/80">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => router.push("/")}>
            <Image src="/outfevibe_logo.png" alt="Outfevibe" width={28} height={28} className="object-contain" />
            <span className="font-bold text-lg tracking-widest">OUTFEVIBE</span>
          </div>
          <Link href="/" className="text-sm text-neutral-400 hover:text-yellow-400 transition">
            ← Back to home
          </Link>
        </div>
      </header>

      {/* HERO */}
      <section className="max-w-5xl mx-auto px-6 pt-16 pb-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-yellow-400/30 bg-yellow-400/5 text-yellow-400 text-xs font-mono tracking-widest uppercase mb-6">
            Legal
          </div>
          <h1 className="text-5xl md:text-6xl font-bold mb-4">Terms of Service</h1>
          <p className="text-neutral-400 text-lg max-w-2xl">
            These terms govern your use of Outfevibe. We've written them in plain language so you actually understand what you're agreeing to.
          </p>
          <p className="text-neutral-600 text-sm mt-4">
            Last updated: {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
          </p>
        </motion.div>
      </section>

      {/* DIVIDER */}
      <div className="max-w-5xl mx-auto px-6">
        <div className="h-px bg-gradient-to-r from-transparent via-neutral-800 to-transparent" />
      </div>

      {/* CONTENT */}
      <section className="max-w-5xl mx-auto px-6 py-12">
        <div className="grid lg:grid-cols-[240px_1fr] gap-12">

          {/* Sticky sidebar TOC */}
          <aside className="hidden lg:block">
            <div className="sticky top-24 space-y-2">
              <p className="text-xs font-mono text-neutral-600 uppercase tracking-widest mb-4">Contents</p>
              {sections.map((s, i) => (
                <a
                  key={i}
                  href={`#section-${i}`}
                  className="block text-sm text-neutral-500 hover:text-yellow-400 transition py-1 border-l-2 border-transparent hover:border-yellow-400 pl-3"
                >
                  {s.title.replace(/^\d+\.\s/, "")}
                </a>
              ))}
            </div>
          </aside>

          {/* Main content */}
          <main className="space-y-12">
            {sections.map((section, i) => (
              <motion.div
                key={i}
                id={`section-${i}`}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.05 }}
                className="scroll-mt-24"
              >
                <h2 className="text-xl font-bold text-white mb-6 pb-3 border-b border-neutral-800">
                  {section.title}
                </h2>
                <div className="space-y-6">
                  {section.content.map((item, j) => (
                    <div key={j}>
                      <h3 className="text-sm font-semibold text-yellow-400 mb-2">{item.subtitle}</h3>
                      <p className="text-neutral-400 text-sm leading-relaxed">{item.text}</p>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </main>

        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-neutral-800 mt-16 py-10 text-center">
        <p className="text-neutral-600 text-sm">
          © {new Date().getFullYear()} Outfevibe ·{" "}
          <Link href="/privacy-policy" className="text-[#d4af7f] hover:underline">Privacy Policy</Link>
          {" · "}
          <Link href="/terms-of-service" className="text-[#d4af7f] hover:underline">Terms of Service</Link>
          {" · "}
          <a href="mailto:outfevibe@gmail.com" className="text-[#d4af7f] hover:underline">Contact</a>
        </p>
      </footer>

    </div>
  );
}